export interface GlossaryTerm {
  term: string;
  definition: string;
  link?: string;
}

export const glossaryTerms: GlossaryTerm[] = [
  { term: '401(k)', definition: 'An employer-sponsored retirement account that lets you contribute a portion of your paycheck, often before tax, into investments that grow until retirement.', link: '/blog/what-is-a-401k/' },
  { term: '403(b)', definition: 'A retirement plan similar to a 401(k), typically offered by public schools, nonprofits, and certain government-adjacent employers.', link: '/blog/403b-vs-401k/' },
  { term: '50/30/20 Rule', definition: 'A budgeting framework that splits after-tax income into roughly 50% needs, 30% wants, and 20% savings or debt repayment.', link: '/blog/50-30-20-budget-rule/' },
  { term: 'APR (Annual Percentage Rate)', definition: 'The yearly cost of borrowing money, typically used for loans and credit cards, generally without accounting for compounding.', link: '/blog/apr-vs-apy/' },
  { term: 'APY (Annual Percentage Yield)', definition: 'The actual amount a deposit account will earn in a year, including the effect of compounding — the standard figure for comparing savings accounts.', link: '/blog/apr-vs-apy/' },
  { term: 'Asset Allocation', definition: 'How your portfolio is divided among different types of investments — typically stocks, bonds, and cash — based on your goals, timeline, and risk tolerance.', link: '/blog/risk-tolerance-and-asset-allocation/' },
  { term: 'Bear Market', definition: 'A period of falling stock prices, commonly defined as a decline of 20% or more from a recent high.', link: '/blog/bull-markets-vs-bear-markets/' },
  { term: 'Bull Market', definition: 'A period of rising stock prices, commonly defined as a gain of 20% or more from a recent low.', link: '/blog/bull-markets-vs-bear-markets/' },
  { term: 'Brokerage Account', definition: 'An account that lets you buy, hold, and sell investments like stocks, bonds, and funds, separate from a bank account used for everyday spending.', link: '/blog/what-is-a-brokerage-account/' },
  { term: 'Catch-Up Contribution', definition: 'An additional amount people 50 and older are permitted to contribute to certain retirement accounts, beyond the standard annual limit.', link: '/blog/catch-up-contributions-after-50/' },
  { term: 'Compound Interest', definition: 'Interest earned on both your original investment and on interest that investment has already earned, causing growth to accelerate over time.', link: '/blog/what-is-compound-interest/' },
  { term: 'Credit Score', definition: 'A number, typically 300-850, estimating how likely you are to repay borrowed money based on your credit history.', link: '/blog/understanding-credit-scores/' },
  { term: 'Credit Utilization', definition: 'The percentage of your available credit (particularly on credit cards) that you\'re currently using — a key factor in most credit scoring models.', link: '/blog/understanding-credit-scores/' },
  { term: 'Debt Avalanche', definition: 'A debt payoff method that directs extra payments toward the debt with the highest interest rate first, minimizing total interest paid.', link: '/blog/debt-payoff-snowball-vs-avalanche/' },
  { term: 'Debt Snowball', definition: 'A debt payoff method that directs extra payments toward the smallest balance first, prioritizing quick psychological wins.', link: '/blog/debt-payoff-snowball-vs-avalanche/' },
  { term: 'Diversification', definition: 'Spreading investments across many different assets to reduce the impact of any single one performing poorly.', link: '/blog/index-funds-vs-individual-stocks/' },
  { term: 'Dividend', definition: 'A portion of a company\'s profits distributed to shareholders, typically on a regular schedule.', link: '/blog/what-are-dividends/' },
  { term: 'Dividend Yield', definition: 'A company\'s annual dividend expressed as a percentage of its current share price, used to compare dividend payments across stocks.', link: '/blog/what-are-dividends/' },
  { term: 'Dollar-Cost Averaging (DCA)', definition: 'Investing a fixed amount at regular intervals regardless of price, rather than investing a lump sum all at once.', link: '/blog/dollar-cost-averaging/' },
  { term: 'Emergency Fund', definition: 'Money set aside specifically to cover unexpected expenses or income loss, kept safe and easily accessible rather than invested.', link: '/blog/build-emergency-fund-before-investing/' },
  { term: 'Employer Match', definition: 'A contribution an employer adds to your retirement account based on your own contribution, up to a certain percentage of salary.', link: '/blog/what-is-a-401k/' },
  { term: 'Envelope Method', definition: 'A budgeting approach that allocates a set amount of money to specific spending categories, stopping when that category\'s "envelope" is empty.', link: '/blog/budgeting-methods-that-actually-work/' },
  { term: 'ETF (Exchange-Traded Fund)', definition: 'A basket of investments that trades on an exchange throughout the day, like a stock, often tracking a market index.', link: '/blog/what-is-an-etf/' },
  { term: 'Expense Ratio', definition: 'The annual fee a fund charges to cover its operating costs, expressed as a percentage of your investment.', link: '/blog/understanding-expense-ratios/' },
  { term: 'FDIC Insurance', definition: 'Federal deposit insurance that protects money in U.S. bank accounts up to a set limit per depositor, per bank, if the bank fails.', link: '/blog/high-yield-savings-accounts-explained/' },
  { term: 'Growth Stock', definition: 'Shares of a company expected to grow revenue and earnings faster than the broader market, often reinvesting profits rather than paying dividends.', link: '/blog/growth-vs-value-investing/' },
  { term: 'High-Yield Savings Account (HYSA)', definition: 'A savings account, often from an online bank, that pays meaningfully more interest than a standard savings account.', link: '/blog/high-yield-savings-accounts-explained/' },
  { term: 'HSA (Health Savings Account)', definition: 'A tax-advantaged account for medical expenses, available to those on a qualifying high-deductible health plan, which can also function as a retirement savings tool.', link: '/blog/hsa-as-a-retirement-tool/' },
  { term: 'Index Fund', definition: 'A fund holding a basket of stocks designed to track a specific market index, such as the S&P 500.', link: '/blog/index-funds-vs-individual-stocks/' },
  { term: 'Inflation', definition: 'The rate at which prices rise over time, which reduces the purchasing power of a fixed amount of money.', link: '/blog/what-is-inflation/' },
  { term: 'Lifestyle Inflation', definition: 'The tendency for spending to rise in step with income, absorbing raises into a more expensive lifestyle rather than increased savings.', link: '/blog/lifestyle-inflation/' },
  { term: 'Lump Sum Investing', definition: 'Investing a full amount of money immediately and all at once, rather than spreading it out over time.', link: '/blog/dollar-cost-averaging-vs-lump-sum/' },
  { term: 'Market Capitalization', definition: 'The total value of a company\'s outstanding shares, calculated as share price multiplied by shares outstanding.', link: '/blog/how-to-read-a-stock-quote/' },
  { term: 'Minimum Payment', definition: 'The smallest amount a lender requires you to pay on a debt each month, often barely covering accrued interest.', link: '/blog/true-cost-of-minimum-payments/' },
  { term: 'Mutual Fund', definition: 'A pooled investment fund, similar to an ETF, but typically priced only once per day rather than trading throughout the day.', link: '/blog/what-is-an-etf/' },
  { term: 'P/E Ratio', definition: 'Price-to-earnings ratio: a company\'s share price divided by its earnings per share, used to gauge how expensive a stock is relative to its profits.', link: '/blog/how-to-read-a-stock-quote/' },
  { term: 'Pay Yourself First', definition: 'A budgeting approach that automatically directs money to savings before any other spending, treating savings as a non-negotiable expense.', link: '/blog/budgeting-methods-that-actually-work/' },
  { term: 'Pension', definition: 'A traditional retirement plan where an employer promises a specific, predictable benefit in retirement and bears the investment risk.', link: '/blog/pensions-vs-401k/' },
  { term: 'REIT (Real Estate Investment Trust)', definition: 'A company that owns or finances income-producing real estate, letting investors gain exposure to property through the stock market.', link: '/blog/what-is-a-reit/' },
  { term: 'Required Minimum Distribution (RMD)', definition: 'The minimum amount the IRS requires you to withdraw annually from certain tax-deferred retirement accounts, starting at a set age.', link: '/blog/required-minimum-distributions-explained/' },
  { term: 'Risk Tolerance', definition: 'Your capacity and willingness to endure fluctuations in investment value in exchange for potentially higher long-term returns.', link: '/blog/risk-tolerance-and-asset-allocation/' },
  { term: 'Roth IRA', definition: 'A retirement account funded with after-tax money, offering tax-free qualified withdrawals in retirement.', link: '/blog/roth-ira-vs-traditional-ira/' },
  { term: 'Sinking Fund', definition: 'Money saved gradually for a specific, predictable future expense, like an annual insurance premium or holiday spending.', link: '/blog/sinking-funds-for-big-expenses/' },
  { term: 'Social Security', definition: 'A U.S. federal program providing retirement income based on lifetime earnings, funded through payroll taxes.', link: '/blog/social-security-basics/' },
  { term: 'Target-Date Fund', definition: 'A single fund that automatically shifts from more stocks to more bonds as a specified target retirement year approaches.', link: '/blog/how-to-choose-401k-investments/' },
  { term: 'Traditional IRA', definition: 'A retirement account funded with pre-tax money, offering an upfront tax deduction while withdrawals are taxed in retirement.', link: '/blog/roth-ira-vs-traditional-ira/' },
  { term: 'Value Stock', definition: 'Shares of a company that appear undervalued relative to their fundamentals, often larger and more established with stable dividends.', link: '/blog/growth-vs-value-investing/' },
  { term: 'Vesting', definition: 'The process of earning full ownership of employer-contributed retirement funds over time, based on a plan\'s vesting schedule.', link: '/blog/401k-vesting-schedules-explained/' },
  { term: 'Zero-Based Budgeting', definition: 'A budgeting method where every dollar of income is assigned a specific job — spending, saving, or debt — until nothing is left unassigned.', link: '/blog/budgeting-methods-that-actually-work/' },
];
